/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-10-30 at 18:32:18 UTC 
 * Modify at your own risk.
 */

package com.appspot.stank_reader.stories.model;

/**
 * Model definition for BReaderNextResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the stories. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BReaderNextResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String bookmark;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean more;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<BReaderStoryMessage> stories;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBookmark() {
    return bookmark;
  }

  /**
   * @param bookmark bookmark or {@code null} for none
   */
  public BReaderNextResponse setBookmark(java.lang.String bookmark) {
    this.bookmark = bookmark;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getMore() {
    return more;
  }

  /**
   * @param more more or {@code null} for none
   */
  public BReaderNextResponse setMore(java.lang.Boolean more) {
    this.more = more;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<BReaderStoryMessage> getStories() {
    return stories;
  }

  /**
   * @param stories stories or {@code null} for none
   */
  public BReaderNextResponse setStories(java.util.List<BReaderStoryMessage> stories) {
    this.stories = stories;
    return this;
  }

  @Override
  public BReaderNextResponse set(String fieldName, Object value) {
    return (BReaderNextResponse) super.set(fieldName, value);
  }

  @Override
  public BReaderNextResponse clone() {
    return (BReaderNextResponse) super.clone();
  }

}
