/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-10-30 at 18:32:18 UTC 
 * Modify at your own risk.
 */

package com.appspot.stank_reader.stories.model;

/**
 * Model definition for BReaderStoryMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the stories. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BReaderStoryMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("feed_guid")
  private java.lang.String feedGuid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("feed_name")
  private java.lang.String feedName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("feed_url")
  private java.lang.String feedUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String link;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("pub_date")
  private java.lang.String pubDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public BReaderStoryMessage setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFeedGuid() {
    return feedGuid;
  }

  /**
   * @param feedGuid feedGuid or {@code null} for none
   */
  public BReaderStoryMessage setFeedGuid(java.lang.String feedGuid) {
    this.feedGuid = feedGuid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFeedName() {
    return feedName;
  }

  /**
   * @param feedName feedName or {@code null} for none
   */
  public BReaderStoryMessage setFeedName(java.lang.String feedName) {
    this.feedName = feedName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFeedUrl() {
    return feedUrl;
  }

  /**
   * @param feedUrl feedUrl or {@code null} for none
   */
  public BReaderStoryMessage setFeedUrl(java.lang.String feedUrl) {
    this.feedUrl = feedUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public BReaderStoryMessage setKey(java.lang.String key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLink() {
    return link;
  }

  /**
   * @param link link or {@code null} for none
   */
  public BReaderStoryMessage setLink(java.lang.String link) {
    this.link = link;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPubDate() {
    return pubDate;
  }

  /**
   * @param pubDate pubDate or {@code null} for none
   */
  public BReaderStoryMessage setPubDate(java.lang.String pubDate) {
    this.pubDate = pubDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public BReaderStoryMessage setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  @Override
  public BReaderStoryMessage set(String fieldName, Object value) {
    return (BReaderStoryMessage) super.set(fieldName, value);
  }

  @Override
  public BReaderStoryMessage clone() {
    return (BReaderStoryMessage) super.clone();
  }

}
