application: fill-me-in
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /api.*
  script: controllers.api.app
  secure: always
- url: /.*
  script: controllers.home.app
  login: admin

libraries:
- name: jinja2
  version: latest
